export { default as Header } from './Header'
export { default as Home } from './Home'
export { default as About } from './About'
// export {default as Collage_Slide} from './Collage_Slide'
export {default as ContactUs}  from './Contact'
// export {default as Icon_Card} from './Icon_Card'
export {default as ImageCard}  from './ImageCard'
export { default as ImageGallery } from './ImageGallery'
// export { default as Footer } from '../components/Footer'
export { default as CanadaAustralia } from '../components/CanadaAustralia'
export { default as MBBSAbroad } from '../components/MBBSAbroad'
export { default as StudyAbroad } from '../components/StudyAbroad'
export { default as StudyIndia } from '../components/StudyIndia'
export { default as UKEurope } from '../components/UKEurope'

